# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
export TERM="xterm-256color"
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias xcopy='xclip -selection clipboard'
alias xpaste='xclip -selection clipboard -o'

export EDITOR=vim

export PATH="$HOME/.local/bin:/opt/ghc/bin:$PATH"

autoload -Uz promptinit
promptinit
prompt powerlevel10k
zstyle ':prezto:load' pmodule
if [ -e /home/axeman/.nix-profile/etc/profile.d/nix.sh ]; then . /home/axeman/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
source /home/axeman/.bash_ansible
source <(kubectl completion zsh)
source <(helm completion zsh)

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
