#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
export TERM="xterm-256color"
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias xcopy='xclip -selection clipboard'
alias xpaste='xclip -selection clipboard -o'

export EDITOR=vim

export PATH="$HOME/.local/bin:/opt/ghc/bin:$PATH"

autoload -Uz promptinit
promptinit
prompt nicoulaj
zstyle ':prezto:load' pmodule
if [ -e /home/axeman/.nix-profile/etc/profile.d/nix.sh ]; then . /home/axeman/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
